/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyectofinal.conectarBBDD;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import com.mysql.jdbc.MysqlDataTruncation;
/**
 *
 * @author ADRI
 */
public class registro extends javax.swing.JFrame {

    conectarBBDD con = new conectarBBDD();
    String genero = "";
    String orsex = "";

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        heteCheck = new javax.swing.JCheckBox();
        homoCheck = new javax.swing.JCheckBox();
        biCheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mascCheck = new javax.swing.JCheckBox();
        femCheck = new javax.swing.JCheckBox();
        aceptarBut = new javax.swing.JButton();
        atrasBut = new javax.swing.JButton();
        provinciaField = new javax.swing.JTextField();
        dateField = new javax.swing.JFormattedTextField();
        surnameField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        contraseñaField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        usuarioField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido/s:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha nacimiento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Provincia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Género:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 50, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Orientación sexual:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        heteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heteCheckActionPerformed(evt);
            }
        });
        getContentPane().add(heteCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        homoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homoCheckActionPerformed(evt);
            }
        });
        getContentPane().add(homoCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        biCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biCheckActionPerformed(evt);
            }
        });
        getContentPane().add(biCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Heterosexual");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bisexual");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Homosexual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Masculino");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Femenino");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        mascCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascCheckActionPerformed(evt);
            }
        });
        getContentPane().add(mascCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        femCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femCheckActionPerformed(evt);
            }
        });
        getContentPane().add(femCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        aceptarBut.setText("ACEPTAR");
        aceptarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        atrasBut.setText("ATRÁS");
        atrasBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButActionPerformed(evt);
            }
        });
        getContentPane().add(atrasBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        provinciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(provinciaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 270, -1));

        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 270, -1));

        surnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, -1));

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 269, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contraseña:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        contraseñaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 270, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Usuario:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        usuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("(YYYY/MM/DD)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Creacion de cuenta");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginverde.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homoCheckActionPerformed
        orsex = "homosexual";
        biCheck.setSelected(false);
        heteCheck.setSelected(false);
    }//GEN-LAST:event_homoCheckActionPerformed

    private void mascCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascCheckActionPerformed
        genero = "masculino";
        femCheck.setSelected(false);
    }//GEN-LAST:event_mascCheckActionPerformed

    private void biCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biCheckActionPerformed
        orsex = "bisexual";
        homoCheck.setSelected(false);
        heteCheck.setSelected(false);
    }//GEN-LAST:event_biCheckActionPerformed

    private void heteCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heteCheckActionPerformed
        orsex = "heterosexual";
        biCheck.setSelected(false);
        homoCheck.setSelected(false);
    }//GEN-LAST:event_heteCheckActionPerformed

    private void femCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femCheckActionPerformed
        genero = "femenino";
        mascCheck.setSelected(false);
    }//GEN-LAST:event_femCheckActionPerformed

    private void provinciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void surnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameFieldActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed

    }//GEN-LAST:event_nombreFieldActionPerformed

    private void atrasButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButActionPerformed
        login ln = new login();
        ln.setVisible(true);
        ln.pack();
        this.dispose();
    }//GEN-LAST:event_atrasButActionPerformed

    private void aceptarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButActionPerformed
        int maxIdVar; 
        try {
            Pattern patron = Pattern.compile("[0-9]{4}/[0-9]{2}/[0-9]{2}");
            Matcher mat= patron.matcher(dateField.getText());
            Statement st=con.getConnection().createStatement();
            ResultSet maxId=st.executeQuery("select coalesce(max(id), -1) as maxId from usuarios");
            maxId.next();
            PreparedStatement insNuevoUsuario = con.getConnection().prepareStatement("INSERT INTO usuarios VALUES (?,?,?,?,?,?,?,?,?,?)");
            if (!(usuarioField.getText().equals("")||contraseñaField.getText().equals("")||nombreField.getText().equals("")||surnameField.getText().equals("")||genero.equals("")||orsex.equals("")||provinciaField.getText().equals("")||dateField.getText().equals(""))){
                insNuevoUsuario.setInt(1, (maxId.getInt("maxId")+1));   
                if (usuarioField.getText().length()<=10){
                    Statement st2=con.getConnection().createStatement();
                    ResultSet usuarios=st2.executeQuery("select * from usuarios where nick ='"+usuarioField.getText()+"'");
                    if (!usuarios.next()){
                        insNuevoUsuario.setString(2, usuarioField.getText());
                    }else{
                        JOptionPane.showMessageDialog(null, "Ya existe el usuario");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nombre de usuario demasiado extenso");
                }
                if (contraseñaField.getText().length()<=20){
                    insNuevoUsuario.setString(3, contraseñaField.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "Contraseña demasiado extensa");
                }
                if(nombreField.getText().length()<=20){
                    insNuevoUsuario.setString(4, nombreField.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "Nombre demasiado extenso");
                }
                if(surnameField.getText().length()<=20){
                    insNuevoUsuario.setString(5, surnameField.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "Apellido demasiado extenso");
                }
                insNuevoUsuario.setString(6, genero);
                insNuevoUsuario.setString(7, orsex);
                if(provinciaField.getText().length()<=35){
                    insNuevoUsuario.setString(8, provinciaField.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "Nombre de província demasiado extenso");
                }
                if (mat.matches()){
                    insNuevoUsuario.setString(9, dateField.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "La fecha no se adecua al formato (YYYY-MM-DD)");
                }    
                insNuevoUsuario.setString(10, "");
                insNuevoUsuario.executeUpdate();
                JOptionPane.showMessageDialog(null, "El registro se ha realizado correctamente");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Completar todos los campos");
            }
        }catch (MysqlDataTruncation ex2 ){
            JOptionPane.showMessageDialog(null, "Fecha errónea");
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_aceptarButActionPerformed

    private void contraseñaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaFieldActionPerformed

    private void usuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }
    
    public void limpiar(){
        heteCheck.setSelected(false);
        biCheck.setSelected(false);
        homoCheck.setSelected(false);
        mascCheck.setSelected(false);
        femCheck.setSelected(false);
        usuarioField.setText("");
        contraseñaField.setText("");
        nombreField.setText("");
        surnameField.setText("");
        dateField.setText("");
        provinciaField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBut;
    private javax.swing.JButton atrasBut;
    private javax.swing.JCheckBox biCheck;
    private javax.swing.JTextField contraseñaField;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JCheckBox femCheck;
    private javax.swing.JCheckBox heteCheck;
    private javax.swing.JCheckBox homoCheck;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mascCheck;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField provinciaField;
    private javax.swing.JTextField surnameField;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
